### ISSUE TITLE
Lỗi sau khi move Zalo

### ISSUE THREAD

**Issue by vhpcdpgl** [NDWoodCompany/ZaloMove#1]
![ảnh](https://github.com/user-attachments/assets/bd400aff-29f2-431c-98c1-8e82d5d1457a)

**Comment by NDWoodCompany** [comment]
B1. Thử chạy với quyền admin hoặc cấp quyền cho thư mục Zalo ở trị trí mới xem có được hay không.
B2. Bạn kiểm tra lại các thư mục xem đã có liên kết chưa nha. Nếu có rồi thì bạn cài lại Zalo. Sau đó kiểm tra lại các thư mục đã được liên kết chưa. Chưa thì liên kết lại rồi đăng nhập zalo.
Lưu ý: Liên kết trước khi đăng nhập Zalo để tránh mất dữ liệu cũ.

**Comment by Saokim999** [comment]
Cho m hỏi đang dùng bt, data để ổ D, xong zalo dạo này hay lỗi out phần mềm. Sau đó nó chạy gì đó như update và giờ dữ liệu lại chọn vè ổ C nên mất hết hiển thị ảnh từ ổ D đã chuyển sang. Vào cài dặt để chuyển về thư mục cũ cũng ko dc out ứng dụng thì làm ntn nhỉ.

**Comment by Saokim999** [comment]
<img width="789" height="559" alt="Image" src="https://github.com/user-attachments/assets/980f834c-8f6c-4758-b630-973a5cf4d2cd" /> chạy liên kết báo có thư mục rồi ko liên kết dc
