### ISSUE TITLE
Lỗi chọn thư mục ở phần D:/Zalo

### ISSUE THREAD

**Issue by hishirooo** [NDWoodCompany/ZaloMove#2]
Khi chọn thư mục Zalo. Click tiếp chọn thư mục ZaloData thì checkbox ở phần Zalo bị mất. 
Tương tự với ZaloData. Nếu chọn ZaloData mà chọn tiếp Zalo thì phần checkbox ở ZaloData sẽ bị mất.
3 mục chọn 
ZaloPC, zalo-updater, Zalo Received Files sẽ tự động checkbox nếu click vào 1 phần chọn khác bất kỳ.
Như vậy tối thiểu sẽ thao tác được trên 2 thự mục và tối đa chỉ là 4 thư mục

https://github.com/user-attachments/assets/e85dc1f3-5c23-4086-957e-b9c2a7ce0a4a

**Comment by NDWoodCompany** [comment]
Chỗ đó chỉ để tạo liên kết thôi. Mình sẽ sửa trong bản cập nhật tới.
Chọn thư mục để liên kết thì bạn chọn bảng bên trái chỗ thư mục gốc rồi ấn TỰ ĐỘNG. di chuyển thủ công thì bấm Cut hoặc Copy. Sau khi di chuyển xong thì click vào bảng bên phải để tạo liên kết.
